### ISSUE TITLE
Why I get a very lower score based on the advice set?

### ISSUE THREAD

**Issue by Jamie-obj** [Ferenas/CPN#1]
I get the mIOU score only have 15.156095005115391, using the train_aug dataset training and using validation dataset to evaluate it. But the SEAM can get a high score just as the paper description.

**Comment by SII-Ferenas** [comment]
could u provide more detail about it？you mean you use the voc12 val set to test the CAM？According to my experiment such settings could lead to 57.41 in voc train set，and i will upload the trained weights if it helps you.

**Comment by Jamie-obj** [comment]
> could u provide more detail about it？you mean you use the voc12 val set to test the CAM？According to my experiment such settings could lead to 57.41 in voc train set，and i will upload the trained weights if it helps you.

Yeah, I'd like to try

**Comment by Jamie-obj** [comment]
> 
> 
> could u provide more detail about it？you mean you use the voc12 val set to test the CAM？According to my experiment such settings could lead to 57.41 in voc train set，and i will upload the trained weights if it helps you.

Could you upload the trained weight, which may help me find the fault

**Comment by SII-Ferenas** [comment]
The well-trained weight for CPN is uploaded, you can find the relevant files in README.md

**Comment by Jamie-obj** [comment]
> 
> 
> The well-trained weight for CPN is uploaded, you can find the relevant files in README.md

Thank you~
