### ISSUE TITLE
pretrained_weight for the initialization of ResNet38 and well-trained CPN

### ISSUE THREAD

**Issue by Shanmukh-C** [Ferenas/CPN#2]
Hello, the link for the pretrained weights is not accessible. Could you please provide the link.

**Comment by SII-Ferenas** [comment]
hi，this may not the link causing the error, I will update the weights to google drive

**Comment by Shanmukh-C** [comment]
> hi，this may not the link causing the error, I will update the weights to google drive
![Screenshot (1784)](https://user-images.githubusercontent.com/85222764/140682492-e23061f7-8141-468a-983b-2c557eabe7f9.png)

This is what is the issue when I open with the existing link it is not opening

**Comment by SII-Ferenas** [comment]
I have uploaded them to Google Drive. I think it is not a link problem since my colleague could successfully enter it. Hope they could help you well.

**Comment by Shanmukh-C** [comment]
> I have uploaded them to Google Drive. I think it is not a link problem since my colleague could successfully enter it. Hope they could help you well.

I am able to use weights now. 
Thank You !

**Comment by SII-Ferenas** [comment]
You are welcome! and feel free to ask any problem if possible
