### ISSUE TITLE
some question about CAM

### ISSUE THREAD

**Issue by lions-heart** [Ferenas/CPN#3]
I`m a fresher in CV. So there's a question about cam.Is it the final segmentation result？Is the final evaluation result calculated by cam and ground truth?

**Comment by SII-Ferenas** [comment]
Not exactly. Actually CAM is an attention map for an image. If we have 20 classes，then an image could have 20 corresponding CAMs and we simply select the CAMs of true labels. After that, we could select the labels for each pixel which  owns the maximum value for CAMs. However, this is not sufficiently used for segmentation task. Thus some methods use the affinity net, which could be an improved CRF, as the post-processing to expand the results obtained by CAM
