### ISSUE TITLE
mxnet version

### ISSUE THREAD

**Issue by bbb-x1** [Ferenas/CPN#6]
Thank you very much for your work, your code is very helpful to me.
When I use your code for training, the following errors occurs:
![error](https://user-images.githubusercontent.com/26369235/154895821-467513fb-4f97-4052-972d-a744f52fe29d.PNG)
I guess it's due to the incompatibility of the MXNET I installed with yours.
Could you tell me what version of MXNET is on your machine?

**Comment by SII-Ferenas** [comment]
HI， YOU CAN CHECK THE VERSION OF THE mxNet here, I have updated the new screenshot, my bad!
![QQ图片20220223151319](https://user-images.githubusercontent.com/55052174/155275359-72d59149-b68c-471a-b7e0-ee7f4b8feef8.jpg)

**Comment by bbb-x1** [comment]
Hi, I'm very sorry I didn't get your point, could you tell me more details?

**Comment by bbb-x1** [comment]
> 

Hi, I'm very sorry I didn't get your point, could you tell me more details?

**Comment by bbb-x1** [comment]
> HI， YOU CAN CHECK THE VERSION OF THE mxNet here, I have updated the new screenshot, my bad! ![QQ图片20220223151319](https://user-images.githubusercontent.com/55052174/155275359-72d59149-b68c-471a-b7e0-ee7f4b8feef8.jpg)

that's so nice for you, thank you for your reply.
